[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "library"
description = "Проект для предмета 'Тестирование'"
authors = [
	{ name="Юрий Волков", email="atribolt@gmail.com" }
]
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
	"tabulate~=0.9.0",
	"PyYAML~=6.0.1"
]

[tool.setuptools.packages.find]
# All the following settings are optional:
include = ["library"]
namespaces = false
